name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: (build rindo ${{ matrix.rindo_version }})
    strategy:
      matrix:
        # Run two different versions in parallel:
        # 1. DEFAULT - uses the version of Rindo written in `package-lock.json`, keeping the same version used by the
        # Rindo team as a source of truth
        # 2. 2 - will install the latest release under major version 2 of Rindo. This should be kept as long as this
        # library supports Rindo v2.Y.Z
        rindo_version: ['DEFAULT', '2']

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      with:
        persist-credentials: false
    - name: Use Node from Volta
      uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # v3.5.0
      with:
        node-version-file: 'package.json'
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
      shell: bash
    - name: Prettier Check
      run: npm run prettier.dry-run
      shell: bash
    - name: Install Rindo ${{matrix.rindo_version}}
      run: npm install --save-dev @rindo/core@${{matrix.rindo_version}}
      shell: bash
      if: ${{ matrix.rindo_version != 'DEFAULT' }}
    - name: Report Rindo Version
      run: npm ls @rindo/core
      shell: bash
    - name: Build
      run: npm run build -- --ci
      shell: bash
    - name: Test
      run: npm run test.ci
      shell: bash
